#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	
	if [ "systemd" == "$INITSYS" ]; then
		ln -s /usr/lib/suporteadaptive/SuporteAdaptive /usr/bin/SuporteAdaptive

		if [ -e /etc/systemd/system/suporteadaptive.service ]; then
			rm /etc/systemd/system/suporteadaptive.service /usr/lib/systemd/system/suporteadaptive.service /usr/lib/systemd/user/suporteadaptive.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/suporteadaptive/files/systemd/suporteadaptive.service /usr/lib/systemd/system/suporteadaptive.service
		systemctl daemon-reload
		systemctl enable suporteadaptive
		systemctl start suporteadaptive
	fi
fi
